# Copyright 2016 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

platform:
  - ARM

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=32
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARGS: --toolset=msvc-14.1 address-model=32  cxxflags=-arch:ARM


install:
  - cd ..
  - git clone -b %APPVEYOR_REPO_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init tools/boost_install
  - git submodule update --init libs/headers
  - git submodule update --init libs/config
  - git submodule update --init libs/assert
  - git submodule update --init libs/bind
  - git submodule update --init libs/core
  - git submodule update --init libs/detail
  - git submodule update --init libs/function
  - git submodule update --init libs/integer
  - git submodule update --init libs/move
  - git submodule update --init libs/mpl
  - git submodule update --init libs/preprocessor
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/throw_exception
  - git submodule update --init libs/type_index
  - git submodule update --init libs/utility
  - git submodule update --init libs/container_hash
  - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\type_traits
  - bootstrap
  - b2 headers

build: off

test_script:
  - cd libs\config\test
  - ..\..\..\b2 config_info_travis_install %ARGS%
  - config_info_travis
  - cd ..\..\type_traits\test
  - ..\..\..\b2 -j3 --hash %ARGS%
